"""initial migration

Revision ID: cc162408811c
Revises: 
Create Date: 2026-08-14 16:25:03.786440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc162408811c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('medicine',
    sa.Column('id_medicine', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('medicine_name', sa.String(length=250), nullable=False),
    sa.Column('dosage', sa.String(length=20), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_medicine')
    )
    op.create_table('schedule',
    sa.Column('id_schedule', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=250), nullable=False),
    sa.Column('message', sa.String(length=250), nullable=False),
    sa.Column('target', sa.String(length=20), nullable=False),
    sa.Column('schedule_time', sa.Time(), nullable=True),
    sa.Column('schedule_end_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_schedule')
    )
    op.create_table('reminder',
    sa.Column('id_reminder', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_medicine', sa.BigInteger(), nullable=True),
    sa.Column('reminder_time', sa.Time(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_medicine'], ['medicine.id_medicine'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_reminder')
    )
    op.create_table('notification',
    sa.Column('id_notification', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_reminder', sa.BigInteger(), nullable=True),
    sa.Column('message', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_reminder'], ['reminder.id_reminder'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_notification')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('reminder')
    op.drop_table('schedule')
    op.drop_table('medicine')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
